language: php
php:
  - '7.0'

install:
  - composer install
  - composer require satooshi/php-coveralls

script:
  - mkdir -p reports
  - php vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls -- --coverage_clover reports/coverage-clover.xml